### ISSUE TITLE
Welcome message or help on Client after successful connection to server

### ISSUE THREAD

**Issue by jp1337** [Dichloromethane/skat#5]
After connecting to a server there is no help or welcome message for the player.
I tried to send come commands to the server but there also was no help.
Maybe the client should get a message like: `You are currently the only player online. Please wait for a second player.`

The commands I tried:
```
test
command: test
0 args
Unknown command: test
> help
command: help
0 args
Unknown command: help
> ?
command: ?
0 args
Unknown command: ?
```

**Comment by iTitus** [comment]
Basic help implemented by 53f3239e8ba1209288792a8c9c60db0073f2c14b
Welcome message added in c23cbb1c8596cf9b9c7fc6891f16f91434b785d1
